### PR TITLE
Add unit tests

### LINKED ISSUE #51: Add unit tests.
#### Definition of the test :
Convert the script based validation tests (all are based on input / output comparisons) [here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/OpenStreetMap_Toolkit/TestProcedure?csf=1&web=1&e=QHj0bC) to unit tests.

### PR DESCRIPTION
**Pull request by rolyhudson**
### Issues addressed by this PR

Closes #51 

Added unit tests.
See [here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/OpenStreetMap_Toolkit/TestProcedure/UnitTests/UnitTestCreation.gh?csf=1&web=1&e=LiA8vZ) for the creation script.
And [here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/OpenStreetMap_Toolkit/TestProcedure/UnitTests/Run_unitTests.gh?csf=1&web=1&e=Xitmwh) for a script to run them.

### CODE REVIEW

**Comment by LMarkowski** [comment]
@BHoMBot check unit tests

**Review by LMarkowski — CHANGES_REQUESTED** [review]
In general everything works very well.

<s>Only thing is that during the workshops we decided that we'll be creating one unit test per .cs file.</s> Could you merge all `ToUTMPolyline` and `QueryBuilder` UTs into two files?

**Erratum:**
Multiple `UnitTest`s per .cs file are correct. So far I've done all of the test creating one `UnitTest` per version of a method (for different inputs). What I meant before was that there should be **one `Dataset` (that can include multiple UnitTests) per .cs file.**

**Comment by rolyhudson** [comment]
@BHoMBot check unit tests

**Review by LMarkowski — APPROVED** [review]
LGTM now!

**Pull request merged**
