### PR TITLE
Add missing references to Dimensional_oM

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

Done in support of https://github.com/BHoM/BHoM/pull/1393/checks?check_run_id=8590783659   

### Issues addressed by this PR

Adding missing references to Dimensional_oM to make sure the toolkit compiles.

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check project compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check project-compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot fix project file ref. 8594103278

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting a force check on: core

**Review by FraserGreenroyd — APPROVED** [review]
Have reviewed the code changes and am satisfied this should resolve the issue reported.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot check serialisation
@BHoMBot check null-handling
@BHoMBot check ready-to-merge

**Pull request merged**
